#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
存量数据导出：本地 data.sqlite → D1 可执行的 INSERT 脚本。

用法（仓库根目录）：
  python workers/scripts/export-sqlite.py [源库路径] [输出文件]
  默认：data.sqlite → workers/scripts/dump-for-d1.sql

导入（workers/ 目录）：
  npx wrangler d1 execute safg-db --local --file scripts/dump-for-d1.sql   # 本地验证
  npx wrangler d1 execute safg-db --remote --file scripts/dump-for-d1.sql  # 正式切换（需 login）

说明：
  - 只导数据不导结构，建表交给 migrations/0001_init.sql（D1 schema 已是最终形态，
    本地库历经多次 ALTER 补列，SELECT * 恰好对齐）；
  - file_name 列暂时原样导出（本地 uploads/ 的文件名）；上传 R2 时由 upload-to-r2.mjs
    统一改写成 R2 key 并回 UPDATE，届时再跑一次 --remote 导入或直接在线 UPDATE；
  - Python 而非 TS：一次性脚本，stdlib sqlite3 就够，省得装依赖。

ASCII-only：本项目脚本铁律（.py 同样遵守，报错信息用英文）。
"""
import sqlite3
import sys
from pathlib import Path

TABLES = ["users", "risk_events", "locations", "payments", "geofences", "recordings"]


def literal(v):
    if v is None:
        return "NULL"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    # TEXT / BLOB(as bytes fallback): single-quote escape, no charset guessing
    if isinstance(v, bytes):
        return "X'%s'" % v.hex()
    s = str(v)
    return "'" + s.replace("'", "''") + "'"


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else "data.sqlite"
    out = Path(sys.argv[2] if len(sys.argv) > 2 else "workers/scripts/dump-for-d1.sql")

    if not Path(src).exists():
        print("ERROR: source db not found: %s" % src)
        sys.exit(1)

    conn = sqlite3.connect(src)
    conn.row_factory = sqlite3.Row
    cur = conn.cursor()

    lines = [
        "-- Auto-generated by export-sqlite.py. Do not edit by hand.",
        "-- Data only; tables must already exist (migrations/0001_init.sql).",
        "PRAGMA foreign_keys = OFF;",
        "",
    ]
    total = 0
    for t in TABLES:
        rows = cur.execute("SELECT * FROM %s" % t).fetchall()
        if not rows:
            lines.append("-- %s: 0 rows" % t)
            lines.append("")
            continue
        cols = rows[0].keys()
        lines.append("-- %s: %d rows" % (t, len(rows)))
        # One multi-row INSERT per table keeps the file small and import fast.
        # D1 execute has a size limit per statement, so chunk every 50 rows.
        for i in range(0, len(rows), 50):
            chunk = rows[i : i + 50]
            values = ",\n  ".join(
                "(" + ", ".join(literal(r[c]) for c in cols) + ")" for r in chunk
            )
            lines.append(
                "INSERT INTO %s (%s) VALUES\n  %s;" % (t, ", ".join(cols), values)
            )
        lines.append("")
        total += len(rows)

    conn.close()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines), encoding="utf-8")
    print("OK: %d rows -> %s (%d bytes)" % (total, out, out.stat().st_size))


if __name__ == "__main__":
    main()
